kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: default
  uid: 3f4aec21-06c5-4246-85d8-0dcc74131b5d
  resourceVersion: '244231139'
  generation: 1
  creationTimestamp: '2024-05-27T09:06:11Z'
  labels:
    karmada.io/managed: 'true'
    propagationpolicy.karmada.io/name: nginx-deployment
    propagationpolicy.karmada.io/namespace: default
    propagationpolicy.karmada.io/permanent-id: 65ce58b9-0593-4704-9340-48647977bab3
    resourcebinding.karmada.io/permanent-id: 3207be8e-8f28-4b8d-be0a-4a3d76d70016
  annotations:
    deployment.kubernetes.io/revision: '1'
    propagationpolicy.karmada.io/name: nginx-deployment
    propagationpolicy.karmada.io/namespace: default
    resourcebinding.karmada.io/name: nginx-deployment
    resourcebinding.karmada.io/namespace: default
    resourcetemplate.karmada.io/managed-annotations: 'propagationpolicy.karmada.io/name,propagationpolicy.karmada.io/namespace,resourcebinding.karmada.io/name,resourcebinding.karmada.io/namespace,resourcetemplate.karmada.io/managed-annotations,resourcetemplate.karmada.io/managed-labels,resourcetemplate.karmada.io/uid,work.karmada.io/conflict-resolution,work.karmada.io/name,work.karmada.io/namespace'
    resourcetemplate.karmada.io/managed-labels: 'karmada.io/managed,propagationpolicy.karmada.io/name,propagationpolicy.karmada.io/namespace,propagationpolicy.karmada.io/permanent-id,resourcebinding.karmada.io/permanent-id'
    resourcetemplate.karmada.io/uid: cb63ce47-4e8e-4b7b-b29f-83e9a1856278
    work.karmada.io/conflict-resolution: abort
    work.karmada.io/name: nginx-687f7fb96f
    work.karmada.io/namespace: karmada-es-fuxi-deploy
  managedFields:
    - manager: fabric8
      operation: Apply
      apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
            'f:propagationpolicy.karmada.io/name': {}
            'f:propagationpolicy.karmada.io/namespace': {}
            'f:resourcebinding.karmada.io/name': {}
            'f:resourcebinding.karmada.io/namespace': {}
            'f:resourcetemplate.karmada.io/managed-annotations': {}
            'f:resourcetemplate.karmada.io/managed-labels': {}
            'f:resourcetemplate.karmada.io/uid': {}
            'f:work.karmada.io/conflict-resolution': {}
            'f:work.karmada.io/name': {}
            'f:work.karmada.io/namespace': {}
          'f:labels':
            'f:karmada.io/managed': {}
            'f:propagationpolicy.karmada.io/name': {}
            'f:propagationpolicy.karmada.io/namespace': {}
            'f:propagationpolicy.karmada.io/permanent-id': {}
            'f:resourcebinding.karmada.io/permanent-id': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                'f:app': {}
                'f:version': {}
            'f:spec':
              'f:containers':
                'k:{"name":"container-1"}':
                  .: {}
                  'f:env':
                    'k:{"name":"PAAS_APP_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PAAS_NAMESPACE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PAAS_PROJECT_ID"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:resources':
                    'f:limits':
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      'f:cpu': {}
                      'f:memory': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:tolerations': {}
    - manager: controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2024-05-27T09:06:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:propagationpolicy.karmada.io/name': {}
            'f:propagationpolicy.karmada.io/namespace': {}
            'f:resourcebinding.karmada.io/name': {}
            'f:resourcebinding.karmada.io/namespace': {}
            'f:resourcetemplate.karmada.io/managed-annotations': {}
            'f:resourcetemplate.karmada.io/managed-labels': {}
            'f:resourcetemplate.karmada.io/uid': {}
            'f:work.karmada.io/conflict-resolution': {}
            'f:work.karmada.io/name': {}
            'f:work.karmada.io/namespace': {}
          'f:labels':
            .: {}
            'f:karmada.io/managed': {}
            'f:propagationpolicy.karmada.io/name': {}
            'f:propagationpolicy.karmada.io/namespace': {}
            'f:propagationpolicy.karmada.io/permanent-id': {}
            'f:resourcebinding.karmada.io/permanent-id': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:version': {}
            'f:spec':
              'f:containers':
                'k:{"name":"container-1"}':
                  .: {}
                  'f:env':
                    .: {}
                    'k:{"name":"PAAS_APP_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PAAS_NAMESPACE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"PAAS_PROJECT_ID"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:tolerations': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2024-05-27T09:06:40Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        version: v1
    spec:
      containers:
        - name: container-1
          image: 'nginx:stable-alpine-perl'
          env:
            - name: PAAS_APP_NAME
              value: nginx
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: 1befb93124ea48b0ae47c681bb4b8d53
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 2
  updatedReplicas: 2
  readyReplicas: 2
  availableReplicas: 2
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2024-05-27T09:06:40Z'
      lastTransitionTime: '2024-05-27T09:06:40Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2024-05-27T09:06:40Z'
      lastTransitionTime: '2024-05-27T09:06:11Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "nginx-777f665474" has successfully progressed.
