kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: default
  uid: 3375d90c-ca33-4dab-897a-9c7d0696947e
  resourceVersion: '351479979'
  generation: 2
  creationTimestamp: '2024-05-27T08:40:56Z'
  labels:
    app: nginx
  annotations:
    asm/put: ''
    asm/updateTimestamp: '2024-05-27T11:20:03Z'
    deployment.kubernetes.io/revision: '2'
  managedFields:
    - manager: fabric8
      operation: Apply
      apiVersion: apps/v1
      time: '2024-05-27T08:40:56Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:asm/put': {}
            'f:asm/updateTimestamp': {}
            'f:deployment.kubernetes.io/revision': {}
          'f:labels':
            'f:app': {}
        'f:spec':
          'f:minReadySeconds': {}
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                'f:asm/updateTimestamp': {}
              'f:labels':
                'f:app': {}
            'f:spec':
              'f:containers':
                'k:{"name":"nginx"}':
                  .: {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:livenessProbe':
                    'f:failureThreshold': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:tcpSocket':
                      'f:port': {}
                    'f:timeoutSeconds': {}
                  'f:name': {}
                  'f:readinessProbe':
                    'f:failureThreshold': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:tcpSocket':
                      'f:port': {}
                    'f:timeoutSeconds': {}
                  'f:resources': {}
                  'f:startupProbe':
                    'f:failureThreshold': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:tcpSocket':
                      'f:port': {}
                    'f:timeoutSeconds': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: cfe-apiserver
      operation: Update
      apiVersion: apps/v1
      time: '2024-05-27T11:20:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:asm/put': {}
            'f:asm/updateTimestamp': {}
        'f:spec':
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:asm/updateTimestamp': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2024-05-27T11:20:24Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
      annotations:
        asm/updateTimestamp: '2024-05-27T11:20:03Z'
    spec:
      containers:
        - name: nginx
          image: nginx
          resources: {}
          livenessProbe:
            tcpSocket:
              port: 80
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 80
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 80
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 20%
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 60
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2024-05-27T11:20:24Z'
      lastTransitionTime: '2024-05-27T11:20:24Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2024-05-27T11:20:24Z'
      lastTransitionTime: '2024-05-27T11:20:03Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "nginx-cc9968685" has successfully progressed.
